before_script:
  - git submodule update --init
  - composer install

unit-tests:
  script:
    - bin/phpunit
  tags:
    - phpunit
  except:
    - tags

code-sniffer:
  script:
    - bin/phpcs --standard=phpcs.xml src
  tags:
    - phpcs
  except:
    - tags
