image: chstudio/php-ci:7.1

stages:
  - check
  - test
  - build

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - sed -i -e "s/http:\/\/127.0.0.1:9200/http:\/\/elasticsearch:9200/" phpunit.xml
  - composer install --no-interaction --prefer-dist

unit-tests:
  stage: test
  services:
    - elasticsearch:2-alpine
    - mysql:latest
  script:
    - vendor/bin/phpunit --coverage-text --colors=never

unit-tests:elasticsearch-1.7:
  stage: test
  services:
    - elasticsearch:1.7-alpine
  script:
    - vendor/bin/phpunit --group elasticsearch

unit-tests:elasticsearch-2.x:
  stage: test
  services:
    - elasticsearch:2-alpine
  script:
    - vendor/bin/phpunit --group elasticsearch

unit-tests:elasticsearch-5.x:
  stage: test
  services:
    - elasticsearch:5-alpine
  script:
    - vendor/bin/phpunit --group elasticsearch
  allow_failure: true

code-sniffer:
  stage: check
  script:
    - vendor/bin/phpcs --standard=phpcs.xml src
