image: chstudio/php-ci:7.1

before_script:
  - composer install --no-interaction --prefer-dist

unit-tests:
  script:
    - bin/phpunit

code-sniffer:
  script:
    - bin/phpcs --standard=phpcs.xml src
